# Generated by Django 2.2 on 2020-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
