# Generated by Django 2.2 on 2019-07-22 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creat_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
