# Generated by Django 2.2 on 2019-09-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sell_price',
            field=models.FloatField(default=0),
        ),
    ]
