# Generated by Django 2.2 on 2019-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='removed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
