# Generated by Django 2.2 on 2019-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='removed',
            field=models.BooleanField(null=True),
        ),
    ]
