# Generated by Django 2.2 on 2019-09-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell_price',
            field=models.FloatField(db_column='s_price', default=0),
        ),
    ]
