# Generated by Django 2.2 on 2019-09-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20190906_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='telephone',
            field=models.IntegerField(max_length=11, null=True, unique=True),
        ),
    ]
