# Generated by Django 2.2 on 2019-09-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190906_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
