# Generated by Django 2.2 on 2019-09-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190906_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='telephone',
        ),
        migrations.AlterModelTable(
            name='book',
            table='author(book)',
        ),
    ]
