# Generated by Django 2.2 on 2019-09-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20190906_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('origin_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Comment')),
            ],
        ),
    ]
