# Generated by Django 2.2 on 2019-09-06 14:06

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(book.models.default_del), to='book.Category'),
        ),
    ]
