# Generated by Django 2.2 on 2019-09-07 02:27

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20190906_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(book.models.default_del), related_name='articles', to='book.Category'),
        ),
    ]
