# Generated by Django 2.2 on 2019-09-10 04:23

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20190907_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(book.models.default_del), to='book.Category'),
        ),
    ]
