# Generated by Django 2.2 on 2019-09-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20190907_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontuser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
